# Generated by Django 4.2.5 on 2023-10-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('education_background', models.CharField(max_length=255)),
                ('mode_of_contact', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('None', 'None')], default='Email', max_length=255)),
            ],
        ),
    ]
