version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code/
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    command: python manage.py runserver 0.0.0.0:8000

