# Generated by Django 4.2.5 on 2023-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HazeSoftFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                (
                    "email",
                    models.CharField(default="bhuwan@example.com", max_length=100),
                ),
                ("nationality", models.CharField(max_length=50)),
                ("dob", models.CharField(max_length=50, verbose_name="Date of Birth")),
                (
                    "education",
                    models.CharField(max_length=50, verbose_name="Education"),
                ),
                (
                    "mode_of_contact",
                    models.CharField(max_length=50, verbose_name="Mode of Contact"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
