# Generated by Django 4.2.5 on 2023-09-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hazesoft_form_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="address",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="dob",
            field=models.DateField(verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="education",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Education",
            ),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="gender",
            field=models.CharField(max_length=50, verbose_name="Gender"),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="middle_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Middle Name",
            ),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="mode_of_contact",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Mode of Contact",
            ),
        ),
        migrations.AlterField(
            model_name="hazesoftformmodel",
            name="nationality",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Nationality",
            ),
        ),
    ]
